services:
    backend:
      restart: unless-stopped
      build: ./backend
      image: laurentaubin/rate-my-degree-backend:latest
      environment:
        DB_HOST: db
      volumes:
        - ./backend/src:/usr/src/app/src
      ports:
        - 4000:4000
      networks:
        - webnet
      depends_on:
        - db
      command: ["./wait-for-it.sh", "db:5432", "--", "node", "dist/index.js"]

    db:
      image: postgres:latest
      environment:
        POSTGRES_PASSWORD: postgres
        POSTGRES_USER: postgres
        POSTGRES_DB: ratemyglo
      volumes:
        - ./data/db:/var/lib/postgresql/data
      ports:
        - "3030:5432"
      networks:
        - webnet
  
  networks:
    webnet:
  