name: ci-frontend
on:
  push:
    branches:
      - "**"
    paths:
      - "frontend/**"

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        working-directory: ./frontend
        run: yarn
      - name: Validate frontend formatting
        working-directory: ./frontend
        run: yarn format:check
