name: ci
on:
  push:
    branches:
      - "**"

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        working-directory: ./backend
        run: yarn
      - name: Validate code formatting
        working-directory: ./backend
        run: yarn format:check

  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        working-directory: ./frontend
        run: yarn
      - name: Validate frontend formatting
        working-directory: ./frontend
        run: yarn format:check
