name: push
on:
  push:
    branches:
      - "**"
    paths-ignore:
      - "**.md"

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Validate frontend code formatting
        run: yarn format:check
        with:
          context: backend/
      - name: Validate backend code formatting
        run: yarn format:check
        with:
          context: backend/
