name: push
on:
  push:
    branches:
      - "**"
    paths-ignore:
      - "**.md"

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install frontend dependencies
        working-directory: ./frontend
        run: yarn
      - name: Install backend dependencies
        working-directory: ./backend
        run: yarn
      - name: Validate frontend code formatting
        working-directory: ./frontend
        run: yarn format:check
      - name: Validate backend code formatting
        working-directory: ./backend
        run: yarn format:check
